### ISSUE TITLE
In Comfort Mode the start in second gear is broken 

### ISSUE THREAD

**Issue by viper-666** [rnd-ash/ultimate-nag52-fw#56]
With the release from 21.02. where a downshift issue is found, there is a problem with the Comfort Mode.
Usually in Comfort Mode the car starts in second gear. Now you can see when you start the car it is in second gear but shifts down immediately with a big jerk.
The good thing about this release is, that it didn't shift in first gear while the car is moving.
That was a big issue in the previous releases.

**Comment by rnd-ash** [comment]
Hey, can you try the latest dev FW, you MUST reset your downshift C map in the map editor first.

**Comment by viper-666** [comment]
Thank you Ashcon for the quick fix!
